name: Terraform CI/CD

on:
  push:
    branches:
      - uat
  pull_request:
    branches:
      - uat

jobs:
  terraform:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'ap-southeast-1'
      TF_VERSION: '1.4.0'
    #   TFLINT_VERSION: '0.46.1'  # Updated to a more recent version
    #   TFSEC_VERSION: '1.28.1'   # Updated to a more recent version

    steps:
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v2

    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Setup ${HOME}/.local/bin path
      run: echo ${HOME}/.local/bin >> $GITHUB_PATH

    - name: PWD
      run: pwd

    - name: List
      run: ls -ltr

    - name: 'Terraform Init'
      run: terraform init --backend-config=env/uat/backend.hcl

    # - name: 'Terraform Format'
    #   run: terraform fmt

    # - name: 'Terraform Validate'
    #   run: terraform validate

    - name: 'Terraform Plan'
      run: terraform plan --var-file=env/uat/terraform.tfvars -out=tfplan 

    - name: 'Terraform Apply'
      if: github.ref == 'refs/heads/uat'
      run: terraform apply -auto-approve tfplan      
